import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import Script from 'next/script'
 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-row justify-center w-full h-full  dark bg-background">
          {children}
      </body>
      <Script
        defer
        src="https://cloud.umami.is/script.js"
        data-website-id={process.env.NEXT_PUBLIC_UMAMI_ID}
        strategy="lazyOnload"
       />
    </html>
  );
}
