import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script'
 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-row justify-center w-full h-full  dark bg-background">
        <div className="max-sm:w-full max-sm:mx-4 md:w-[600px] lg:w-[800px] xl:w-[1000px] 2xl:w-[1300px]">
          {children}
        </div>
      </body>
      <Script
        async
        src="https://umami-victor.vercel.app/script.js"
        data-website-id="a7bcb790-3d79-478e-a7ed-3c46810fbb4f"
       />
    </html>
  );
}
